# Generated by Django 6.0.4 on 2026-04-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneUrbaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Zone Urbaine',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('longueur_km', models.FloatField(default=1.0)),
                ('nb_voies', models.IntegerField(default=2)),
                ('vitesse_limite', models.IntegerField(default=50)),
                ('sens', models.CharField(choices=[('1', 'Sens unique'), ('2', 'Double sens')], default='2', max_length=1)),
                ('etat', models.CharField(choices=[('ouvert', 'Ouverte'), ('ferme', 'Fermée'), ('travaux', 'En travaux')], default='ouvert', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('intersections', models.ManyToManyField(blank=True, related_name='routes', to='traffic.intersection')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.zoneurbaine')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='intersection',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.zoneurbaine'),
        ),
    ]
