# Generated by Django 6.0.4 on 2026-04-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traffic', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('accident', 'Accident'), ('blocage', 'Route bloquée'), ('congestion', 'Congestion'), ('travaux', 'Travaux'), ('urgence', 'Urgence')], max_length=20)),
                ('description', models.TextField()),
                ('localisation', models.CharField(max_length=300)),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('grave', 'Grave'), ('critique', 'Critique')], default='moyen', max_length=10)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_cours', 'En cours de résolution'), ('resolu', 'Résolu')], default='actif', max_length=20)),
                ('duree_estimee', models.IntegerField(default=30, help_text='Durée estimée en minutes')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('route_alternative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_pour', to='traffic.route')),
                ('routes_impactees', models.ManyToManyField(blank=True, related_name='incidents', to='traffic.route')),
                ('vehicules_impactes', models.ManyToManyField(blank=True, related_name='incidents', to='vehicles.vehicule')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
