# Generated by Django 6.0.4 on 2026-04-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('voiture', 'Voiture'), ('bus', 'Bus'), ('camion', 'Camion'), ('moto', 'Moto'), ('electrique', 'Électrique'), ('prioritaire', 'Prioritaire')], max_length=20)),
                ('vitesse_moyenne', models.FloatField(default=0)),
                ('etat', models.CharField(choices=[('actif', 'En circulation'), ('arrete', 'Arrêté'), ('recharge', 'En recharge'), ('mission', 'En mission')], default='arrete', max_length=20)),
                ('point_depart', models.CharField(blank=True, max_length=200)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('niveau_batterie', models.FloatField(blank=True, help_text='% pour véhicules électriques', null=True)),
                ('mission_statut', models.CharField(blank=True, max_length=100)),
                ('priorite', models.IntegerField(default=0, help_text='Niveau de priorité (0=normal, 1-3=prioritaire)')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('route_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='traffic.route')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(choices=[('ambulance', 'Ambulance'), ('pompiers', 'Pompiers'), ('police', 'Police')], max_length=20)),
                ('description', models.TextField()),
                ('depart', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('intersection_prioritaire', models.ManyToManyField(blank=True, to='traffic.intersection')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='vehicles.vehicule')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
