# Generated by Django 6.0.4 on 2026-04-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeuCirculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('rouge', '🔴 Rouge'), ('orange', '🟠 Orange'), ('vert', '🟢 Vert')], default='rouge', max_length=10)),
                ('duree_rouge', models.IntegerField(default=30, help_text='Durée rouge (secondes)')),
                ('duree_vert', models.IntegerField(default=25, help_text='Durée vert (secondes)')),
                ('duree_orange', models.IntegerField(default=5, help_text='Durée orange (secondes)')),
                ('mode', models.CharField(choices=[('fixe', 'Fixe'), ('adaptatif', 'Adaptatif')], default='fixe', max_length=15)),
                ('actif', models.BooleanField(default=True)),
                ('derniere_modif', models.DateTimeField(auto_now=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feux', to='traffic.intersection')),
            ],
            options={
                'verbose_name': 'Feu de Circulation',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueFeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_etat', models.CharField(max_length=10)),
                ('nouvel_etat', models.CharField(max_length=10)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.CharField(blank=True, max_length=200)),
                ('feu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='signals.feucirculation')),
            ],
            options={
                'ordering': ['-date_changement'],
            },
        ),
    ]
