# Generated by Django 6.0.4 on 2026-04-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traffic', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=300)),
                ('capacite_totale', models.IntegerField(default=100)),
                ('places_disponibles', models.IntegerField(default=100)),
                ('tarif_horaire', models.FloatField(default=5.0, help_text='Tarif en MAD/heure')),
                ('ouvert', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.zoneurbaine')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='BorneRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('type_charge', models.CharField(choices=[('lente', 'Lente (AC)'), ('rapide', 'Rapide (DC)'), ('ultra', 'Ultra-rapide')], default='rapide', max_length=10)),
                ('puissance_kw', models.FloatField(default=22.0)),
                ('etat', models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupée'), ('panne', 'En panne')], default='libre', max_length=10)),
                ('debut_recharge', models.DateTimeField(blank=True, null=True)),
                ('duree_estimee', models.IntegerField(blank=True, help_text='Minutes', null=True)),
                ('vehicule_en_charge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borne_recharge', to='vehicles.vehicule')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bornes', to='parking.parking')),
            ],
            options={
                'verbose_name': 'Borne de Recharge',
            },
        ),
    ]
